### ISSUE TITLE
Single digit dates can't be added with report start.

### ISSUE THREAD

**Issue by jonatanlindstrom** [jonatanlindstrom/chrono#20]
Single digit dates result in a bad string because of right justification.

```
$ chrono report start 8:25
Traceback (most recent call last):
  File "/usr/local/bin/chrono", line 9, in <module>
    load_entry_point('chrono==1.0b2', 'console_scripts', 'chrono')()
  File "/usr/local/lib/python3.4/site-packages/chrono-1.0b2-py3.4.egg/chrono/chrono.py", line 171, in main
  File "/usr/local/lib/python3.4/site-packages/chrono-1.0b2-py3.4.egg/chrono/writer.py", line 17, in write_line
chrono.errors.ReportError: Bad report string: " 2. 8:25"
```

**Comment by jonatanlindstrom** [comment]
Fixed by #23
